
//EMPLOYEE POPUP TYPES
export const EMPLOYEE_POPUP_TYPE:string='EMPLOYEE'

//COMPANY POPUP TYPE
export const COMPANY_POPUP_TYPE:string='COMPANY'

//ACCOUNTING_PLAN POPUP TYPE
export const ACCOUNTING_PLAN_POPUP_TYPE:string='ACCOUNTING_PLAN'
